import { Pool } from "pg";
export const db = 
`CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, 
    isAdmin BOOLEAN DEFAULT false, 
    PRIMARY KEY(id)
);
`;

/**
 * Connection to your psql database 
 * (using local db for now)
 */
export const pool = new Pool({
  user: "postgres",
  host: "postgres_db",
  database: "postgres",
  password: "postgres",
  port: 5432,
});


export async function seedDb() {
  const conn = await pool.connect();
  console.log("initialising");
  conn.query(db);
  console.log("users db initialised");
}

