import { Pool } from "pg";

const POSTGRES_PASSWORD= `cs3219-g27`;
const POSTGRES_DB= `postgres`;
const POSTGRES_USER= `postgres`;
const POSTGRES_HOST= `34.142.136.87`;
const POSTGRES_PORT= 5432;

export const db = 
`CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL, 
  isAdmin BOOLEAN DEFAULT false, 
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS attempted_qns (
  id INT,
  qid TEXT NOT NULL,
  attempted_date TIMESTAMP NOT NULL,
  attempt TEXT,
  isCompleted BOOLEAN DEFAULT false,
  FOREIGN KEY(id) REFERENCES users(id)
);`;

/**
 * Connection to your psql database 
 * (using local db for now)
 */

//change the fields as you need, but this should be the default
export const pool = new Pool({
  user: "postgres",
  host: "postgres_db",
  database: "postgres",
  password: "postgres",
  port: 5432,
});


export async function seedDb() {
  const conn = await pool.connect();
  console.log("initialising");
  conn.query(db);
  console.log("users db initialised");
}
