version: "3.3"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    links:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    ports:
      - "27017:27017"
