export const db = 
`DROP TABLE IF EXISTS users, user_info, attempted_qns, completed_qns CASCADE;
CREATE TABLE users (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, 
    PRIMARY KEY(id)
);
CREATE TABLE user_info (
    id INT PRIMARY KEY,
    dname TEXT NOT NULL,
    pic_path TEXT DEFAULT '',
    FOREIGN KEY(id) REFERENCES users(id)
);`;
