import { Pool } from "pg";

/**
 * Connection to your psql database 
 * (using local db for now)
 */

//change the fields as you need, but this should be the default
export const pool = new Pool({
    user: "postgres",
    host: "localhost",
    database: "postgres",
    password: "postgres",
    port: 5432,
});

const query = 
`DROP TABLE IF EXISTS users, user_info, attempted_qns, completed_qns CASCADE;
CREATE TABLE users (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, 
    isAdmin BOOLEAN DEFAULT false, 
    PRIMARY KEY(id)
);
CREATE TABLE user_info (
    id INT PRIMARY KEY,
    dname TEXT NOT NULL,
    pic_path TEXT DEFAULT '',
    FOREIGN KEY(id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS attempted_qns (
    id INT PRIMARY KEY,
    qid TEXT NOT NULL,
    attempted_date TIMESTAMP NOT NULL,
    FOREIGN KEY(id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS completed_qns (
    id INT,
    qid TEXT NOT NULL,
    completed_date TIMESTAMP NOT NULL,
    FOREIGN KEY(id) REFERENCES users(id)
);`

export async function seedDb() {
    const conn = await pool.connect();
    conn.query(query);
    console.log("users db initialised");
}
